# Generated by Django 4.1.7 on 2023-03-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('quantidade_estoque', models.IntegerField()),
                ('quantidade_critica', models.IntegerField()),
                ('numero_serie', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='media')),
            ],
        ),
    ]
