# Generated by Django 4.1.7 on 2023-03-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(upload_to='produtos'),
        ),
    ]
